config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations',
    passwords:     'users/passwords',
    confirmations: 'users/confirmations'
  }

  namespace :teacher do
    resources :dashboard, only: %i[index]
  end

  namespace :student do
    resources :dashboard, only: %i[index]
    resources :companies do
      resources :transactions, only: %i[new create]
    end
  end
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  CURRENCIES = %W[USD EUR GBP PKR]

  belongs_to :user
  has_one :cash, dependent: :destroy

  validates :name, :country_of_incorporation, :currency, presence: true

  accepts_nested_attributes_for :cash, reject_if: :all_blank
end

app/controllers/student/base_controller.rb
# frozen_string_literal: true

class Student::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_student

  def authenticate_student
    return redirect_to root_path, alert: 'Access Denied! you are not authorized to access this page.' unless current_user.student?
  end
end

app/controllers/student/companies_controller.rb
# frozen_string_literal: true

class Student::CompaniesController < Student::BaseController
  before_action :set_company, only: %i[edit update show destroy]

  def index
    @companies = Company.all
  end

  def new
    @company = Company.new
    @company.build_cash
  end

  def create
    @company = current_user.companies.new(company_params)

    if @company.save
      redirect_to student_companies_path, notice: 'Company was successfully created.'
    else
      @company.build_cash
      render :new
    end
  end

  def edit; end

  def update
    if @company.update(company_params)
      redirect_to student_companies_path, notice: 'Company was successfully updated.'
    else
      render :edit
    end
  end

  def show
    @cash = @company.cash
  end

  def destroy
    @company.destroy
    redirect_to student_companies_path, notice: 'Company was successfully destroyed.'
  end

  private

  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:name, :country_of_incorporation, :currency, cash_attributes: %i[initial_balance])
  end
end

app/controllers/student/dashboard_controller.rb
# frozen_string_literal: true

class Student::DashboardController < Student::BaseController
  def index; end
end

app/controllers/student/transactions_controller.rb
# frozen_string_literal: true

class Student::TransactionsController < Student::BaseController
  before_action :load_company

  def new
    @transaction = @cash.transactions.new(nature: Transaction.natures.key(params[:cash].to_i))
  end

  def create
    transaction = @cash.transactions.new(transaction_params)

    if transaction.save
      flash[:notice] = 'New cash in has been created successfully!'
    else
      flash[:alert] = transaction.errors.full_messages.to_sentence
    end

    redirect_to student_company_path(@company.id)
  end

  private

  def load_company
    @company = Company.find(params[:company_id])
    @cash    = @company.cash
  end

  def transaction_params
    params.require(:transaction).permit(:nature, :category, :other, :amount)
  end
end

app/helpers/student/base_helper.rb
# frozen_string_literal: true

module Student::BaseHelper
end

app/helpers/student/companies_helper.rb
module Student::CompaniesHelper
end

app/helpers/student/dashboard_helper.rb
# frozen_string_literal: true

module Student::DashboardHelper
end

app/helpers/student/transactions_helper.rb
module Student::TransactionsHelper
end

app/views/student/companies/edit.html.erb
<%= render 'student/companies/partials/form', company: @company %>

app/views/student/companies/index.html.erb
<div class="mb-2">
  <%= link_to 'New Company', new_student_company_path, class: 'btn btn-primary' %>
</div>
<% if @companies.present? %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Country of Incorporation</th>
        <th scope="col">Currency</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @companies.each do |company| %>
        <tr>
          <td><%= company.name %></td>
          <td><%= company.country_of_incorporation %></td>
          <td><%= company.currency %></td>
          <td>
            <%= link_to 'Show', student_company_path(company), class: 'btn btn-sm btn-primary' %>
            <%= link_to 'Edit', edit_student_company_path(company), class: 'btn btn-sm btn-primary' %>
            <%= link_to 'Delete', student_company_path(company), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-primary' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div>No Companies Yet!</div>
<% end %>

app/views/student/companies/new.html.erb
<%= render 'student/companies/partials/form', company: @company %>

app/views/student/companies/show.html.erb
<div class="mb-2">
  <%= link_to 'Cash In', new_student_company_transaction_path(@company.id, cash: Transaction.natures['cash_in']), remote: true, class: 'btn btn-primary' %> |
  <%= link_to 'Cash Out', new_student_company_transaction_path(@company.id, cash: Transaction.natures['cash_out']), remote: true, class: 'btn btn-primary' %>
</div>

<div class="mb-3 mt-3">
  <h1>Current Account Balance</h1>
  <div><%= @cash.remaining_balance %></div>
</div>

<div class="mb-3 mt-3">
  <h1>Monthly Balance History</h1>
  <% if @cash.monthly_balance.present? %>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Month</th>
          <th scope="col">Balance</th>
        </tr>
      </thead>
      <tbody>
        <% @cash.monthly_balance.each do |k, v| %>
          <tr>
            <td><%= k %></td>
            <td><%= v %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div>No Monthly History Yet!</div>
  <% end %>
</div>

<hr>

<div class="mb-3 mt-3">
  <h1>Transaction History</h1>
  <% if @cash.transactions.present? %>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Type</th>
          <th scope="col">Category</th>
          <th scope="col">Amount</th>
          <th scope="col">Month</th>
        </tr>
      </thead>
      <tbody>
        <% @cash.transactions.each do |transaction| %>
          <tr>
            <td><%= transaction.nature.humanize %></td>
            <td><%= transaction.category == 'Other' ? "#{transaction.category} (#{transaction.other})" : transaction.category  %></td>
            <td><%= transaction.amount %></td>
            <td><%= transaction.created_at.strftime('%m-%Y') %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div>No Transaction History Yet!</div>
  <% end %>
</div>



<div id="new-transaction-modal-container"></div>