config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations',
    passwords:     'users/passwords',
    confirmations: 'users/confirmations'
  }

  namespace :teacher do
    resources :dashboard, only: %i[index]
  end

  namespace :student do
    resources :dashboard, only: %i[index]
    resources :companies do
      resources :transactions, only: %i[new create]
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cash.rb
# frozen_string_literal: true

class Cash < ApplicationRecord
  belongs_to :company
  has_many :transactions, dependent: :destroy

  MONTHLY_BALANCE_KEY = '{{MONTH}}-{{YEAR}}'

  before_create :build_remaining_balance

  class << self
    def build_monthly_balance_key(month, year)
      MONTHLY_BALANCE_KEY.gsub('{{MONTH}}', month.to_s).gsub('{{YEAR}}', year.to_s)
    end
  end

  private

  def build_remaining_balance
    self.remaining_balance = initial_balance
  end
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  CURRENCIES = %W[USD EUR GBP PKR]

  belongs_to :user
  has_one :cash, dependent: :destroy

  validates :name, :country_of_incorporation, :currency, presence: true

  accepts_nested_attributes_for :cash, reject_if: :all_blank
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :cash

  CASH_IN_CATS  = ['Revenues', 'Equity', 'Convertible Note', 'Bank Debt', 'Other']
  CASH_OUT_CATS = ['COGS', 'Employees', 'Services', 'Other Operating Expenses', 'Investments', 'Other']

  enum nature: %w[cash_in cash_out]

  before_create :check_monthly_balance_key
  after_create :deduct_remaining_balance

  private

  def check_monthly_balance_key
    monthly_balance_key = Cash.build_monthly_balance_key(DateTime.now.month, DateTime.now.year)
    return if cash.monthly_balance.key?(monthly_balance_key)

    monthly_balance = self.cash.monthly_balance.dup
    monthly_balance[monthly_balance_key] = cash.remaining_balance
    cash.update_column(:monthly_balance, monthly_balance)
  end

  def deduct_remaining_balance
    if cash_in?
      remaining_balance = cash.remaining_balance + amount
    else
      remaining_balance = cash.remaining_balance - amount
    end
    cash.update_column(:remaining_balance, remaining_balance)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_one_attached :avatar
  has_many :companies

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  enum role: %w[teacher student]

  validates :name, :surname, :role, :email, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/student/base_controller.rb
# frozen_string_literal: true

class Student::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_student

  def authenticate_student
    return redirect_to root_path, alert: 'Access Denied! you are not authorized to access this page.' unless current_user.student?
  end
end

app/controllers/teacher/base_controller.rb
# frozen_string_literal: true

class Teacher::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_teacher

  def authenticate_teacher
    return redirect_to root_path, alert: 'Access Denied! you are not authorized to access this page.' unless current_user.teacher?
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_class(key)
    key == 'alert' ? 'danger' : 'success'
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/student/base_helper.rb
# frozen_string_literal: true

module Student::BaseHelper
end

app/helpers/student/companies_helper.rb
module Student::CompaniesHelper
end

app/helpers/student/dashboard_helper.rb
# frozen_string_literal: true

module Student::DashboardHelper
end

app/helpers/student/transactions_helper.rb
module Student::TransactionsHelper
end

app/helpers/teacher/base_helper.rb
# frozen_string_literal: true

module Teacher::BaseHelper
end

app/helpers/teacher/dashboard_helper.rb
# frozen_string_literal: true

module Teacher::DashboardHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cash Management</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/partials/header' %>
    <%= render 'layouts/partials/flash' %>
    <div class="container">
      <div class="mt-5">
        <%= yield %>
      </div>
    </div>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/layouts/partials/_flash.html.erb
<% flash.each do |key, msg| %>
  <div class="alert alert-<%= flash_class(key) %> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/partials/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Cash Management</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: 'nav-item nav-link' %>
      </li>
      <% if current_user&.teacher? %>
        <li>
          <%= link_to 'Dashboard', teacher_dashboard_index_path, class: 'nav-item nav-link' %>
        </li>
      <% elsif current_user&.student? %>
        <li>
          <%= link_to 'Dashboard', student_dashboard_index_path, class: 'nav-item nav-link' %>
        </li>
        <li>
          <%= link_to 'Companies', student_companies_path, class: 'nav-item nav-link' %>
        </li>
      <% end %>
    </ul>
    <span class="navbar-text">
      <% if current_user.present? %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Login', new_user_session_path %> |
        <%= link_to 'Signup', new_user_registration_path %>
      <% end %>
    </span>
  </div>
</nav>